### ISSUE TITLE
Getting 502 Bad Gateway

### ISSUE THREAD

**Issue by denisbobovnik** [teal33t/poopak#5]
I would like some help with setting up poopak V1 on Docker for Windows. I installed with powerschell terminal and all went good but uppon opening localhost i get "502 Bad Gateway". ANy steps to follow if this happens? im kinda new with docker and cant find any solutions so far.

**Comment by teal33t** [comment]
Hi @denisbobovnik 
Can you put docker log for 'web-app' container?
May you have some conflicted configuration on your machine with web server, are you running any other web server?

**Comment by denisbobovnik** [comment]
Hey @teal33t 
It might be running but i'm not 100% sure since i did a lot of school web projects on this machine but that was like 1-2 years ago and i think i uninstalled most services responsible for running web servers by now.. anyway here's the log:

`Waiting 25 seconds before checking for hosts availability
Checking availability of mongodb:27017
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Host mongodb:27017 not yet availabile
Timeout! After 30 seconds some hosts are still not reachable`

soo..i guess mongo is the problem? i did use to have a mongodb server locally but i think i already removed it long ago

**Comment by teal33t** [comment]
@denisbobovnik Hey, you can check your machine for usage of mongo with this command
`lsof -i | grep mongo
`
check it and come back again

**Comment by denisbobovnik** [comment]
I'm actually trying to find this but it seems this is a linux command? i'm on windows and i tried some mongod cmd commands and nothing is registered under mongod..therefore no mongo running i guess?
