### ISSUE TITLE
Adding onion removes `:` from `http://somesite.onion` and results in 503

### ISSUE THREAD

**Issue by anoduck** [teal33t/poopak#9]
Got it running, but when I attempt to add a site for poopak to crawl, it removes the colon `:` from the site address. Which then causes poopak to fail crawling the site, always returning a 503 error code. So instead of retrieving and crawling `http://somesite.onion` poopak attempts to retrieve and crawl `http//somesite.onion` which is not an address at all. Small bug, but creates a huge problem. I have tried using `'http:/somesite.onion'` which did not work.

**Comment by teal33t** [comment]
Got, it will fix this. thanks

**Comment by anoduck** [comment]
Thanks, I hope it is an easy fix.

**Comment by huseyin5920** [comment]
any solution found?

**Comment by anoduck** [comment]
@huseyin5920 I have not attempted to run the crawler since encountering this error, and due to time restraints. I highly suggest you open up a new issue and reference this one, since this issue has already been closed by the developer. I also encourage you to do what I failed to do and provide the developer with enough information so he may be able to recreate the bug himself. 

Best of luck.
